version: '3'
services:
 c-db:
  build: ./db/.
  ports: 
    - "3306:3306"
  volumes:
   - c-db:/var/lib/mysql
  restart: always
 c-php:
  build: ./php/.
  ports:
   - "80:80"
  restart: always
  environment:
   - IS_Container=dev
  volumes:
   - D:/xampp/htdocs/Connect:/var/www/html
  depends_on:
   - c-db
 c-phpmyadmin:
  build: ./phpmyadmin/.
  ports:
   - "8081:80"
  depends_on:
   - c-db
  restart: always
 c-cron:
  build: ./cron/.
  restart: always
volumes:
 c-db:
