version: '3'
services:
 c-db:
  build: ./db/.
  ports: 
    - "3306:3306"
  volumes:
   - c-db:/var/lib/mysql
  restart: always
 c-php:
  build: ./php/.
  ports:
   - "81:80"
  restart: always
  volumes:
   - /home/eitea/Schreibtisch/Connect/html:/var/www/html
  depends_on:
   - c-db
 c-phpmyadmin:
  build: ./phpmyadmin/.
  ports:
   - "8081:80"
  depends_on:
   - c-db
  restart: always
 c-cron:
  build: ./cron/.
  restart: always
 c-smtp:
  build: ./smtp/.
  restart: always
  ports:
   - "26:25"
  volumes:
   - /home/eitea/Schreibtisch/Connect/fake-smtp-output:/output
 c-minio:
  image: minio/minio
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: "AKIAIOSFODNN7EXAMPLE"
   MINIO_SECRET_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  volumes:
   - c-minio:/data
  command: server /data
 c-imap:
  image: antespi/docker-imap-devel:latest
  ports:
   - "25:25"
   - "143:143"
   - "993:993"
  environment:
   - MAILNAME=example.org
   - MAIL_ADDRESS=address@example.org
   - MAIL_PASS=pass
volumes:
 c-db:
 c-minio:
